Repository RobotlegsJS/RobotlegsJS-Pixi, pull requests merged in 2018-08, with the labels that each got.

#71 Update TypeScript Compiler Options
  .gitignore
  .npmignore
  CHANGELOG.md
  karma.conf.js
  package.json
  tsconfig.json
  tsconfig.test.json
  tslint.json
  webpack.config.js
  yarn.lock
Labels: enhancement

#68 'added' event is not emited until child has access to stage
  src/robotlegs/bender/extensions/contextView/pixiPatch/pixi-patch.ts
  test/robotlegs/bender/extensions/contextView/pixiPatch/pixiPatch.test.ts
Labels: bug

#72 Only dispatch 'added' or 'removed' events when view is related to current stage
  CHANGELOG.md
  package.json
  src/robotlegs/bender/extensions/contextView/pixiPatch/pixi-patch.ts
  test/robotlegs/bender/extensions/contextView/pixiPatch/pixiPatch.test.ts
Labels: bug

#75 Update dependencies to latest version 🚀
  package.json
  yarn.lock
Labels: greenkeeper

#76 Move pixi.js and eventemitter3 libraries to peerDependencies
  CHANGELOG.md
  README.md
  package.json
  yarn.lock
Labels: enhancement

#78 Improve example project
  .npmignore
  CHANGELOG.md
  README.md
  example/Game.ts
  example/config/MyConfig.ts
  example/index.ts
  example/mediator/RobotlegsMediator.ts
  example/mediator/SmileyMediator.ts
  example/view/ChildMediator.ts
  example/view/ChildView.ts
  example/view/CircleMediator.ts
  example/view/CircleView.ts
  example/view/RobotlegsView.ts
  example/view/SmileyView.ts
  package.json
  static/images/loading.gif
  static/images/pixijs-v4-logo.png
  static/images/robotlegs.png
  static/index.html
  static/manifest.json
  static/scripts/cache-polyfill.js
  static/service-worker.js
  static/styles/example.css
  static/styles/main.css
  webpack.example.config.js
  yarn.lock
Labels: enhancement

#79 Update dependencies to latest version 🚀
  package.json
  yarn.lock
Labels: greenkeeper
