Repository RobotlegsJS/RobotlegsJS-Pixi, pull requests merged in 2020-02, with the labels that each got.

#122 Update pixi.js to version 5.2.1 🚀
  .gitignore
  CHANGELOG.md
  README.md
  example/Game.ts
  example/view/RobotlegsView.ts
  package.json
  src/robotlegs/bender/extensions/contextView/pixiPatch/contains-patch.ts
  src/robotlegs/bender/extensions/contextView/pixiPatch/eventemitter3-patch.ts
  src/robotlegs/bender/extensions/contextView/pixiPatch/pixi-patch.ts
  src/robotlegs/bender/extensions/mediatorMap/impl/MediatorFactory.ts
  static/images/pixijs-v4-logo.png
  static/images/pixijs-v5-logo.png
  static/styles/main.css
  yarn.lock
Labels: enhancement, greenkeeper

#125 Migrate to terser-webpack-plugin
  CHANGELOG.md
  package.json
  webpack.config.js
  webpack.example.config.js
  yarn.lock
Labels: greenkeeper

#126 Add repository funding file
  .github/FUNDING.yml
  CHANGELOG.md
Labels: enhancement

#127 Add enterprise support information with Tidelift
  CHANGELOG.md
  README.md
Labels: enhancement

#129 Update tslib to the latest version 🚀
  CHANGELOG.md
  package.json
  yarn.lock
Labels: greenkeeper
